version: '2.1'
services:
  trolley:
    build: .
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis
    ports:
      - 8080:8080
  redis:
    image: redis
    ports:
      - 6380:6380
    expose:
      - 6379
